server:
  port: ${SERVER_PORT:8082}

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:notice_board}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:woo960525!}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: false
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
        hbm2ddl:
          charset_name: utf8mb4
    show-sql: true

# FastAPI 서버 URL
fastapi:
  url: ${FASTAPI_URL:http://localhost:8000}
