server:
  port: 8082

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://localhost:3306/notice_board?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: woo960525!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: false
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
        hbm2ddl:
          charset_name: utf8mb4
    show-sql: true
